config/routes.rb
Rails.application.routes.draw do

   root 'sessions#new'

   match '/login',    to: 'sessions#new',     via: 'get'
   match '/logout',   to: 'sessions#destroy', via: 'delete'

   resources :hospital
   resources :admin
   resources :user
   resources :education
   resources :sessions
   resources :group
   resources :department

  
end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password

	has_many :departments
	belongs_to :hospital

	validates_presence_of :name
  validates_presence_of :email


  def name
  	"#{first_name} #{last_name}"
 	end


end

app/models/department.rb
class Department < ActiveRecord::Base

	belongs_to :admin
	belongs_to :hospital
	has_many :groups
end

app/models/education.rb
class Education < ActiveRecord::Base

	belongs_to :user
	
end

app/models/group.rb
class Group < ActiveRecord::Base

	belongs_to :department
	has_many :users
	
end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

	has_many :admins
	has_many :departments
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :group
	has_many :educations


	def name
  	"#{first_name} #{last_name}"
 	end

 	end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :correct_user
	def index
	 @admin = Admin.find(params[:id])
	end

	def show
  @admin = Admin.find(params[:id])
  @hospital = @admin.hospital
  @departments = @hospital.departments
	end
end


private

def correct_user
@user = User.find(params[:id]) 
redirect_to admin_url(session[:user_id]) unless session[:user_id] == @user.id
end 

app/controllers/education_controller.rb
class EducationController < ApplicationController
end

app/controllers/group_controller.rb
class GroupController < ApplicationController


	def index

	end

	def show 
		@group = Group.find(params[:id])
		@employees = @group.users
	end


end

app/controllers/hospital_controller.rb
class HospitalController < ApplicationController

	def show 
		hos = Hospital.find(params[:id])
		dep = hos.departments
		gro = dep.each(&:groups)
   @users = gro.each(&:users)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
  end

  def create
    user = Admin.find_by(email: params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:error] = "Invalid email and/or password"
      render 'new'
    end
  end

  def destroy
    session.clear
    redirect_to :root
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController

	def index

	end

	def show

		@user = User.find(params[:id])
		@education = @user.educations
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/hospital_helper.rb
module HospitalHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end



end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/show.html.erb
<% if current_user %>
<%= link_to 'Sign Out', logout_path, method: "delete" %>
<% end %>

<h1>Welcome <%= @admin.name %></h1>
<h4>Hospital: <%= @admin.hospital.name %></h4>
	
	<ul>
		<% @departments.each do |dep| %>
		<li>Department: <%= link_to dep.name, department_path(dep) %>
				<ul>
					<% dep.groups.each do |group| %>
					<li>
						<%= link_to group.name, group_path %>
					</li>
						<% end %>
				</ul>
		</li>
   <% end %>


	</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- nav bar-->

<div class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Tracker</a>
      <div class="nav-collapse">
        <ul class="nav">
          <% if current_user %>
          <li><%= link_to "Main Menu", admin_path %></li>
          
          <li><button type="button" class="btn btn-warning btn-lg"><%= link_to 'Sign Out', logout_path, method: "delete" %> </button></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

<!-- end nav bar -->
<div class="container">
  <div class="row">
    <div class="span9"><%= yield %></div>
    <div class="span3">
      <h2>About Us</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>        
    </div>
  </div>
</div>
</body>
</html>